print('Hello NUISTWF GitHub!')
print('U->untracked 未追踪状态, A->added 增加到暂存区仓库里, M->Modifed 被修改状态')
print('git config --global http.sslVerify "false"')
print('每次提交信息都会产生一个版本号, 版本号此时包含了上次操作parent的版本号以及tree当前目录各个文件最新的版本号')
print('分支并没有产生备份的仓库, 只是在当前提交的文件信息中指向不同的文件进行操作')
